version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    expose: ["5432"]
    networks:
      - backend_network

  backend:
    image: todo-backend
    build:
      context: ./../BACKEND/
      dockerfile: Dockerfile
    volumes: 
      - /data/springboot-docker-compose-app
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: unless-stopped
    links:
      - postgres:localhost
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    backend-todo:
