version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    expose: ["5432"]

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  backend:
    image: todo-backend
    build:
      context: ./../BACKEND/
      dockerfile: Dockerfile
    volumes: 
      - /data/springboot-docker-compose-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    links:
      - postgres:localhost

networks:
  postgres:
    driver: bridge
  

volumes:
    postgres:
    pgadmin:
    backend-todo:
